In [2]:
import tensorflow as tf

In [8]:
a=tf.constant(100)
print(a)

tf.Tensor(100, shape=(), dtype=int32)


In [9]:
a = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32, name='a')
print(a)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [11]:
a=tf.constant([[1,6,5],[2,3,4]])
print(a)

# tf.argmax(input,axis)根据axis取值的不同返回每行或者每列最大值的索引。
# axis=0时比较每一列的元素，将每一列最大元素所在的索引记录下来，最后输出每一列最大元素所在的索引数组。
# axis=1的时候，将每一行最大元素所在的索引记录下来，最后返回每一行最大元素所在的索引数组。
print(tf.argmax(a,0))
print(tf.argmax(a,1))

tf.Tensor(
[[1 6 5]
 [2 3 4]], shape=(2, 3), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)


In [15]:
a = tf.constant([[1, 1, 1], [2, 2, 2]])
print(a)
print(tf.reduce_sum(a))
print(tf.reduce_sum(a,0))
# print(tf.reduce_sum(a,0,keep_dims=True)) tf2.0中没有keep_dims
print(tf.reduce_sum(a,1))


tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([3 6], shape=(2,), dtype=int32)


In [17]:
a = tf.constant([[1, 0, 0], [0, 1, 1]])
print(a)
print(tf.equal(a,1))
print(tf.not_equal(a,1))

tf.Tensor(
[[1 0 0]
 [0 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ True False False]
 [False  True  True]], shape=(2, 3), dtype=bool)
tf.Tensor(
[[False  True  True]
 [ True False False]], shape=(2, 3), dtype=bool)


In [19]:
# normal=tf.random_normal([3],stddev=0.1)
normal=tf.random.normal([3],stddev=0.1) # tf2.0中改名了
print(normal)

tf.Tensor([-0.04289964  0.09093744  0.01092483], shape=(3,), dtype=float32)


In [21]:
var=tf.Variable(tf.random.normal([3],stddev=0.1),name='var')
print(var.name)
print(var)

var:0
<tf.Variable 'var:0' shape=(3,) dtype=float32, numpy=array([0.06447488, 0.00387952, 0.12176509], dtype=float32)>


In [23]:
var2 = tf.Variable(tf.random.normal([2, 3], stddev=0.1), name='my_var')
var3 = tf.Variable(tf.random.normal([2, 3], stddev=0.1), name='my_var')
print(var2.name)
print(var3.name)

my_var:0
my_var:0
